### ISSUE TITLE
url issue: config REACT_APP_API_URL  in k8s env does not work

### ISSUE THREAD

**Issue by bellondr** [change-metrics/monocle#1006]
When I deploy monocle on k8s in aws elk. I found that the frond end will post  localhost:8080/api/v2/about
I config REACT_APP_API_URL in k8s env, it does not work.
How to config serverUrl?

```
let serverUrl = %raw(`
  (window.API_URL !== '__API_URL__' ? window.API_URL : process.env.REACT_APP_API_URL || '')
`)

```

**Comment by morucci** [comment]
I'm closing the issue. Please re-open if needed.
