### ISSUE TITLE
OIDC authentication issue

### ISSUE THREAD

**Issue by k-Gangadhar** [change-metrics/monocle#1007]
Hi Team,

I'm not able to setup OIDC authentication for Monocle. I'm able to generate the JWT token from monocle server but login page is not redirecting to OIDC authentication. It says unauthenticated login. Could you please help me?

**Comment by morucci** [comment]
Hi,

Have you added the auth section into the monocle configuration ? https://github.com/change-metrics/monocle#oidc-provider
And have you set both required environment variables MONOCLE_PUBLIC_URL and MONOCLE_OIDC_<PROVIDER_NAME>_CLIENT_SECRET ?

When you say that you are able to generate a JWT from the Monocle server, are you talking about https://github.com/change-metrics/monocle#service-tokens ? Please note that this kind of token is for third party apps that consume the Monocle API but not for regular users using the Monocle UI.

**Comment by morucci** [comment]
By using the last master image you might get ore insight from the logs thanks to https://github.com/change-metrics/monocle/pull/1008

**Comment by ramsudhakar90** [comment]
I'm also facing same issue. I have pulled the latest master code. How do I get the logs ?

**Comment by morucci** [comment]
docker-compose logs api

**Comment by ramsudhakar90** [comment]
@morucci I'm not seeing anything about OIDC in the logs. And Its not taking OIDC login.

![screenshot-azure-test linkstreet co-2022 12 26-17_13_19](https://user-images.githubusercontent.com/69676343/209545239-55685083-06fa-4272-8a56-8ec198eb6bb7.png)

**Comment by morucci** [comment]
If you are using the master container images then you should see a log warning about oidc. It is one of the first log lines when the api starts. Perhaps Ensure you have the auth section configured in config file and copy the first logs Line here.

**Comment by ramsudhakar90** [comment]
![Screenshot (116)](https://user-images.githubusercontent.com/69676343/209547809-3e8f100b-b36f-42b0-af82-c4f1baaf3c6b.png)

2022-12-26 12:11:20 INFO    Monocle.Backend.Index:422: Ensure workspace  {"index":"monocle.changes.1.monocle"}
2022-12-26 12:11:52 INFO    Monocle.Backend.Index:413: Ensure schema version {"version":4}
2022-12-26 12:11:52 INFO    Monocle.Main:169: SystemReady {"workspace":1,"port":8080,"elastic":"http://elastic:9200"}

**Comment by ramsudhakar90** [comment]
@morucci Any update??

**Comment by morucci** [comment]
Hi,

Could you try with the last published image. Last image includes more logs about the OIDC init: https://github.com/change-metrics/monocle/pull/1008/files

To do so (if using the docker-compose deployment) set in .env:
`COMPOSE_MONOCLE_VERSION=latest`

then
```
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by ramsudhakar90** [comment]
Now getting this

![image](https://user-images.githubusercontent.com/69676343/210346043-5671b4fb-6efe-4893-b186-a51744689d02.png)

**Comment by morucci** [comment]
It seems that the JSON content returned by the URL:  "<oidc_issuer_url>/.well-known/openid-configuration" is not as expected.
Note that ".well-known/openid-configuration" is appended to the URL you set in the configuration https://hackage.haskell.org/package/oidc-client-0.7.0.1/docs/src/Web.OIDC.Client.Discovery.html#discover

The returned document must follow the same format as https://accounts.google.com/.well-known/openid-configuration

**Comment by ramsudhakar90** [comment]
@morucci That's perfect. Works now. Thanks a lot :)
