### ISSUE TITLE
[Network]:Error connecting for remote machine

### ISSUE THREAD

**Issue by rahmanih** [change-metrics/monocle#1036]
Hi,
Again it is simply awesome 🎊!

I succeeded to get monocle running on my local machine, however when trying to connect on it from a remote machine on same network LAN, I got the following error:
![image](https://github.com/change-metrics/monocle/assets/3645021/6f8e5e51-93fe-43f7-a78a-663d93a507b5)

on the local machine I can see the following log:
```
10.157.21.182 - - [12/May/2023:09:03:44 +0100] "GET /monocle/ HTTP/1.1" 200 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35"
10.157.21.182 - - [12/May/2023:09:03:44 +0100] "GET /dist/RedHatText-Regular-KL2IF35V.woff2 HTTP/1.1" 200 - "http://10.157.21.235:8080/dist/bundle.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35"
10.157.21.182 - - [12/May/2023:09:03:46 +0100] "GET /dist/RedHatText-Medium-ZUMCJ74Z.woff2 HTTP/1.1" 200 - "http://10.157.21.235:8080/dist/bundle.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35"
```
Am I missing something in the config?

regards
haithem

**Comment by morucci** [comment]
Hi,

Please check MONOCLE_PUBLIC_URL in https://github.com/change-metrics/monocle#environment-variables that's probably what that is missing on your setup.

Regards

**Comment by morucci** [comment]
Please re-open if needed.
