### ISSUE TITLE
Github token expired situation

### ISSUE THREAD

**Issue by epaillous** [change-metrics/monocle#1060]
Hello there! 
First of all, thank you for this project : I've used it some months ago and was able to retrieve some data for my teams!
However, I've stopped using it during 2 months, so my github token expired. I've regenerate new one, and try to replace it in the .secrets but it seems that the crawler can not fetch data anymore, here is the error I get : 
```
 WARNING Lentille.GitHub.RateLimit:62: Unexpected error {"index":"my_index","crawler":"github-my-crawler","stream":"Changes","err":"\"FetchErrorNoResult\""}
```

I've tried to wipe all data from the crawler (even if I do not really want to do that because it took some times to retrieve it 😅 ) but the command failed : 
```
docker-compose run --rm --no-deps api monocle janitor wipe-crawler-data --elastic elastic:9200 --config /etc/monocle/config.yaml --workspace my-workspace --crawler-name my-crawler

Invalid argument `wipe-crawler-data'

Usage: monocle janitor COMMAND
  Maintain the database

```

Any ideas ? 😇

**Comment by morucci** [comment]
Hi Emilie,

The `wipe-crawler-data` command is part of the last release 1.9.0 so be sure to bump your deployment to this release. See the blog post here for the procedure to follow: https://changemetrics.io/posts/2023-09-17-version-1.9.0-release.html

However to replace an expired token, usually you just have to:

- generate a new token (be sure to read the section about the old and new fine grained token https://github.com/change-metrics/monocle#change)
- stop the crawler process with: `docker-compose stop crawler`
- update the `.secrets` file
- start the crawler process with: `docker-compose start crawler`

**Comment by morucci** [comment]
No the delay did not changed. However there is a new setting for configuring it if you want to change the default: https://github.com/change-metrics/monocle/pull/1033

**Comment by epaillous** [comment]
Hi @morucci,
thanks for your quick answer! 
Not sure it works, I have added the loop_delay in my config.yaml like this : 
```
workspaces:
  - name: my-workspace
    crawlers:
      - name: github-my-crawler
        provider:
          github_organization: my-org
          github_repositories:
            - my-repo
        update_since: '2023-04-01'
        loop_delay_sec: 120
```
stop and start the crawler by doing : 
```
docker-compose stop crawler
docker-compose start crawler
```
but it seems that the crawler is still fetching only every 600 seconds 😢 
Moreover, despite the `update_since: '2023-04-01'` it seems that since I've regenerate my token it does not fetch old data, see this : 
<img width="540" alt="Capture d’écran 2023-09-19 à 11 39 00" src="https://github.com/change-metrics/monocle/assets/4488722/62476187-39ba-4ce3-b044-0199faf840bc">

I should have data during july and august 😢 
Do you have any clue on what's happening ?

**Comment by morucci** [comment]
Hi,

Yes multiple things here:

- It seems that the crawler still commit its crawling point even when such failure happen ("FetchErrorNoResult") which seems to be related to an expired GH token. The crawler should not do that. I have to double check in the code why.
- By design a crawler crawls resources (here PRs) updated after the crawling point (it is a date). So due to ^ and this design then that expected you see not data.

The monocle CLI does not provide a command to reset the crawling point to the one defined in the configuration. I'll see if I can provide such command.

Until I have a fix, the only way is to wipe data related to that crawler using https://github.com/change-metrics/monocle#wipe-crawler-data-from-the-database

**Comment by morucci** [comment]
Also the `loop_delay_sec` must be defined in a specific `crawlers` key at the root of the YAML (same level than `workspaces`)
