### ISSUE TITLE
Target branch in the ChangeMergedEvent

### ISSUE THREAD

**Issue by leonid-deriv** [change-metrics/monocle#1065]
Hi 

why we do not have a target branch in the ChangeMergedEvent. target branch exists in Change event but this is not very handy :(
Can we add a target branch to ChangeMergedEvent?

**Comment by morucci** [comment]
Hi,

Thanks for the report, you are right and I see that adding the "branch" filter in the query leads to empty graphs in the web ui. So yes there is a bug here. I can provide a fix soon. Or let me know if you'd like to tackle that issue.

**Comment by leonid-deriv** [comment]
If you can add a target branch in the ChangeMErged event, it will be great. 
To tackle this I was thinking of using Kibana and run-time lookup fields but they are only supported in Elastic 8.2... so the question are you planning to update Elastic version soon?

**Comment by morucci** [comment]
> If you can add a target branch in the ChangeMErged event, it will be great.

The fix adds the `target_branch` field to all change events including the `ChangeMergedEvent`. The fix does not bring any upgrade procedure so that means only events docs related to updated or new changes will get the field.

> To tackle this I was thinking of using Kibana and run-time lookup fields but they are only supported in Elastic 8.2... so the question are you planning to update Elastic version soon?

We should update it yes. Here is the related issue #1067
