### ISSUE TITLE
Add merge_commit_sha to Change event

### ISSUE THREAD

**Issue by leonid-deriv** [change-metrics/monocle#1072]
Can we add merge_commit_sha to the Change event?

Currently, only code commits are included. We believe this should not be very difficult.
We need to correlate merge_commits to the deployment events. This may help with this issue as well - https://github.com/change-metrics/monocle/issues/277

Here is from GitHub docs

The value of the **merge_commit_sha** attribute changes depending on the state of the pull request. Before merging a pull request, the merge_commit_sha attribute holds the SHA of the test merge commit. After merging a pull request, the merge_commit_sha attribute changes depending on how you merged the pull request:

- If merged as a [merge commit](https://docs.github.com/articles/about-merge-methods-on-github/), merge_commit_sha represents the SHA of the merge commit.

- If merged via a [squash](https://docs.github.com/articles/about-merge-methods-on-github/#squashing-your-merge-commits), merge_commit_sha represents the SHA of the squashed commit on the base branch.

- If [rebased](https://docs.github.com/articles/about-merge-methods-on-github/#rebasing-and-merging-your-commits), merge_commit_sha represents the commit that the base branch was updated to.

**Comment by morucci** [comment]
Hi,

Thanks for the feedback. Yes that might be possible. Could you provide some precision ?

- Is `mergeCommit` the field you expect to be used from the PullRequest object https://docs.github.com/en/graphql/reference/objects#pullrequest ?
- When you refer to the "Change event" are you referring to the Change's object or an event object such as the ChangeMergedEvent object ?

**Comment by leonid-deriv** [comment]
1. yes, I expect to see mergeCommit. If we have commit SHA I hope it should be enough. is it oid or abbreviatedOid.
2. I refer to type:"Change".  But maybe it is a good idea to also add it to ChangeMergedEvent? No? So if you ask me it is better to add to both, if only one - to the "Change"
