### ISSUE TITLE
Display "name" instead of account name

### ISSUE THREAD

**Issue by JdumaresqSE** [change-metrics/monocle#1110]
Hi, 

Is it possible to show the name instead of the account name ? 

Example:
My name is John Doe but my account name is toto1234

In the web interface I only see toto1234. I would like to see John Doe instead.  Is that possible ?

Thanx !

**Comment by morucci** [comment]
Hi,

Yes that's possible, see https://github.com/change-metrics/monocle?tab=readme-ov-file#identity-management

**Comment by JdumaresqSE** [comment]
I have updated the confir.yaml and it was not working. But I recheck the example and we need to remove the https:// before the url in the aliases section. Now it's working

Thanx
