### ISSUE TITLE
Investigate if we could write a gitlab crawler

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#209]
To do so:

- https://github.com/change-metrics/monocle/blob/master/CONTRIBUTING.md#contributing-a-new-driver
- Ensure the GitLab API provides needed endpoints and data that fit into the Monocle schema.

**Comment by eedri** [comment]
+1 for this, we would love to add the internal gitlab server.
Where can someone find instructions on how to write a new crawler?

**Comment by morucci** [comment]
Hi Eyal,

A GitLab driver for Monocle would be a great addition to the project. I took time to document a bit more how to develop a driver. See https://github.com/change-metrics/monocle/blob/master/monocle/dummy/change.py that is driver skeleton that can be use as a starting point. There are also some comments to help.

Any questions and help requests in this ticket will be welcome. We will be happy to help if you intend to develop the driver.

Fabien

**Comment by Omeramsc** [comment]
As I discussed with Fabian, I'd love to take care of it.

**Comment by morucci** [comment]
@Omeramsc Let me know if you need guidance. Also do not hesitate to propose partial or buggy code then I could help to move forward with the driver.

**Comment by morucci** [comment]
WIP here: https://github.com/change-metrics/lentille/pull/20
