### ISSUE TITLE
Invalid interpolation format for "environment" option in service "web": "${MONOCLE_TITLE:-}"

### ISSUE THREAD

**Issue by Levi-Armstrong** [change-metrics/monocle#270]
Hello,

I am currently working through the instruction and when starting the docker I get the error in the title. Not sure what file to edit to correct the issue.

1. https://github.com/change-metrics/monocle#clone-and-create-the-needed-directories
1. https://github.com/change-metrics/monocle#create-the-configyaml-file
1. https://github.com/change-metrics/monocle#start-docker-compose

**Comment by Levi-Armstrong** [comment]
I was able to solve the issue by opening the docker-compose.yml and and changing `${MONOCLE_TITLE:-}` to `${MONOCLE_TITLE:-ROS-Industrial}`

**Comment by morucci** [comment]
Hi, could you tell me which version of docker-compose are you using ?


Le ven. 6 nov. 2020 à 06:34, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by morucci** [comment]
See #227 . related to docker-compse version. Closing
