### ISSUE TITLE
Access Organization with Restricted Access 

### ISSUE THREAD

**Issue by Levi-Armstrong** [change-metrics/monocle#271]
I current am an owner on a Organization for which we would like to use this tool. I have went through the process of create the Github App under the organization and created the rsa key. Inside the docker-compose.yml file I updated `'${GITHUB_APP_ID:-}` and saved the rsa in the etc folder with the app_key.rsa. I then ran the `docker-compose up -d` command and then `docker-compose ps`. I check the the status multiple time until there is an Exit 0 for the crawler. Thought when I view the statistics it is empty. I then print the log for the crawler and I see multiple `blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];'}` which leads me to believe something else is not configured correctly. Any ideas what might be the issue?

**Comment by morucci** [comment]
It looks like to be elasticsearh error. Could you check elastic container
logs ?
You might want try a full restart of all containers.


Le ven. 6 nov. 2020 à 06:43, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
I found a thread on elasticsearch related to TOO_MANY_REQUESTS and it looks like it means I am running out of disk space. I am testing it on one of my personal repositories and it was also getting this error. So I was at about 90% disk usage so I freed up about 50GB and on the simple repository the crawler would finish in about 60sec and now it has been running for about 10minutes and I am not seeing the TOO_MANY_REQUESTS error any more. Once this finished I will try it again on the organization repository and report. back. 

Though I do see error being printed out about unable to extract PR because of missing value for author. Is this an issue?

**Comment by morucci** [comment]
Yes it is, I've experienced a lot of corner cases with the data received
from the github api. If you are able to identify which PR  is missing the
author field please let me know which one and I'll find a fix for the
crawler.

Le ven. 6 nov. 2020 à 07:29, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
Is this the information you need?

Repository: https://github.com/Levi-Armstrong/tesseract_ros_workcell

``` bash
crawler_1  | 2020-11-06 13:59:14,246 - monocle.github.pullrequest - 139760637213472 - Levi-Armstrong/tesseract_ros_workcell - ERROR - Unable to extract PR
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/dacite/core.py", line 56, in from_dict
crawler_1  |     field_data = data[field.name]
crawler_1  | KeyError: 'author'
crawler_1  | 
crawler_1  | During handling of the above exception, another exception occurred:
crawler_1  | 
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/dacite/core.py", line 68, in from_dict
crawler_1  |     value = get_default_value_for_field(field)
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
crawler_1  |     raise DefaultValueNotFoundError()
crawler_1  | dacite.dataclasses.DefaultValueNotFoundError
crawler_1  | 
crawler_1  | During handling of the above exception, another exception occurred:
crawler_1  | 
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/monocle-0.7.0-py3.8.egg/monocle/github/pullrequest.py", line 545, in extract_objects
crawler_1  |     objects.extend(extract_pr_objects(pr))
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/monocle-0.7.0-py3.8.egg/monocle/github/pullrequest.py", line 475, in extract_pr_objects
crawler_1  |     change["commits"].append(from_dict(data_class=Commit, data=obj))
crawler_1  |   File "/usr/local/lib/python3.8/site-packages/dacite/core.py", line 72, in from_dict
crawler_1  |     raise MissingValueError(field.name)
crawler_1  | dacite.exceptions.MissingValueError: missing value for field "author"
```

**Comment by morucci** [comment]
oh ok, so the master is broken, I'll try to fix it asap but in the meantime
you should use a released version, the last one is 0.7.0.
Let's try to use it by setting MONOCLE_VERSION. Please see the explanations
here
https://github.com/change-metrics/monocle#clone-and-create-the-needed-directories

Le ven. 6 nov. 2020 à 14:04, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
Well, I believe I am currently using 0.7.0. Below is what I have in my docker-compose.yml. Is this the correct place to set the version?

```
image: "changemetrics/monocle_backend:${MONOCLE_VERSION:-0.7.0}"
```

**Comment by morucci** [comment]
I've just tried with 0.7.0 with your repo tesseract_roh_workcell and it
went well.

Please check the image you are using with docker-compose images. You should
see 0.7.0 for api, crawler and web containers.

You should not overwrite the compose file directly but instead create a
.env file with the MONOCLE_VERSION setting like explained in the README.

cat .env
MONOCLE_VERSION=0.7.0


Le ven. 6 nov. 2020 à 15:40, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
Ah, so does the .env go in the same directory as the docker-compose.yml?

**Comment by morucci** [comment]
yes

Le ven. 6 nov. 2020 à 17:59, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
Alright so I create the .env with the content below. I then run things again and I get the following error.

error:
```


.env:
```
ERROR: Invalid interpolation format for "environment" option in service "web": "${MONOCLE_TITLE:-}"
```

MONOCLE_VERSION=0.7.0
GITHUB_CLIENT_ID=XXXX
GITHUB_CLIENT_SECRET=XXXX
GITHUB_APP_ID=XXX
GITHUB_APP_KEY_PATH=/etc/monocle/app_key.pem
MONOCLE_TITLE=ROS-Industrial
```

**Comment by morucci** [comment]
Could you tell me which docker-compose version you are using and the
platform ?

I'm running Fedora Linux with docker-compose
[fabien@localhost ~]$ docker-compose --version
docker-compose version 1.25.4, build unknown

Le ven. 6 nov. 2020 à 18:09, Levi Armstrong <notifications@github.com> a
écrit :

**Comment by Levi-Armstrong** [comment]
I am on Ubuntu 18.04 and docker-compose version 1.17.1.

**Comment by Levi-Armstrong** [comment]
so I upgraded to 1.2.7 and now the .env works. Everything now works with my personal repositories, but when I try to do a repository under the ros-industrial-consortium organization I get the following error. I followed the instructions for add a GitHub app and added the information to the .env.

``` bash
crawler_1  | 2020-11-06 22:35:49,735 - monocle.github.graphql - 140706274917152 - ros-industrial-consortium/tesseract - ERROR - Errors in response: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `C0E6:21E5:4CFA6E:DC2036:5FA5CFAD` when reporting this issue.'}]}
```

**Comment by Levi-Armstrong** [comment]
Even though I am getting the error above it does now seem to be working with the upgrade to docker-compose 1.27. Is the error above an issue?

**Comment by morucci** [comment]
No it isn't. The timeout is a legitimate issue when querying PR data from the GitHub API. Depending on the amount of PRs and size of each PRs the API may return a timeout.
So the Monocle crawler is adaptative and you can see it in the log below. It starts by trying to get 100 PRs, then it got a timeout, so it tried on 50 PRs, then it passed, so it increased to 56, ...

So everything looks fine now, happy it from from your side :+1: 

Can I close the issue ?

```
crawler_1  | 2020-11-07 07:05:31,896 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - Running request {'org': 'elastic', 'repository': 'ecs', 'updated_since': datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': '', 'total_prs_count': 0, 'size': 100}
crawler_1  | 2020-11-07 07:05:43,605 - monocle.github.graphql - 140344055511840 - elastic/ecs - ERROR - Errors in response: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `BBC8:A943:55117B:60775E:5FA6473C` when reporting this issue.'}]}
crawler_1  | 2020-11-07 07:05:43,605 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - Running request {'org': 'elastic', 'repository': 'ecs', 'updated_since': datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': '', 'total_prs_count': 0, 'size': 50}
crawler_1  | 2020-11-07 07:05:52,219 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - Total PRs: 693 but will fetch until we reached a PRupdated at date < 2000-01-01 00:00:00+00:00
crawler_1  | 2020-11-07 07:05:52,223 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - 50 PRs fetched
crawler_1  | 2020-11-07 07:05:52,223 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - Running request {'org': 'elastic', 'repository': 'ecs', 'updated_since': datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': 'after: "Y3Vyc29yOnYyOpK0MjAyMC0xMC0zMFQwODoyNzoxM1rOFdynQA=="', 'total_prs_count': 693, 'size': 56}
crawler_1  | 2020-11-07 07:06:02,692 - root - 140344055511840 - elastic/ecs - INFO - page oldest updated at date is 2020-10-02 21:08:05+00:00
crawler_1  | 2020-11-07 07:06:02,692 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - 106 PRs fetched
crawler_1  | 2020-11-07 07:06:02,693 - monocle.github.pullrequest - 140344055511840 - elastic/ecs - INFO - Running request {'org': 'elastic', 'repository': 'ecs', 'updated_since': datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': 'after: "Y3Vyc29yOnYyOpK0MjAyMC0xMC0wMlQyMTowODowNVrOG8qw3Q=="', 'total_prs_count': 693, 'size': 62}
```

**Comment by Levi-Armstrong** [comment]
Thanks for the help. Everything is working!
