### ISSUE TITLE
ConnectionTimeout while starting crawler

### ISSUE THREAD

**Issue by Larissayk** [change-metrics/monocle#276]
Has anyone face this problem while starting crawler? 
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout
TimeoutError(HTTPConnectionPool(host='elastic', port=9200): Read timed out. (read timeout=10))

ps: demo instance also not working anymore

**Comment by morucci** [comment]
Hi, thanks for the report.

The demo server has been restarted by my provider and the service did not properly restart. The demo node is up now.

Regarding the timeout log in the crawler logs, as the ElasticSearch container take some seconds to be up and ready, the crawler loop on connection attempt until it connects to ElasticSearch.

If it finally connects to ElasticSearch after few second then that's the normal behavior that you are seeing.

**Comment by morucci** [comment]
Please reopen if needed.
