### ISSUE TITLE
Install on Centos

### ISSUE THREAD

**Issue by dominic-git** [change-metrics/monocle#286]
There is no documentation for installing monocle in Centos (version: 7)?
I installed successfully on localhost but got an error on centos

**Comment by morucci** [comment]
Hello @dominic-git, the underlying system should not cause so much trouble when deploying Monocle. The first step is to ensure docker and docker-compose are installed and behave as expected. Then deploying Monocle should be as explained in the Readme. The documentation does not cover the Docker and docker-compose installation.

Feel free to share the error you are faced with, w/o it won't be able to help so much.

Thanks

**Comment by morucci** [comment]
Closing please re-open if needed.
