### ISSUE TITLE
Exception when running against a private github repo

### ISSUE THREAD

**Issue by sooraj19** [change-metrics/monocle#287]
Hi Team,

I have followed the set up as per the readme. My config is pointing to a private github repo which does have a few open PRs. But I can see that crawler is failing to fetch any PR information.

**Crawler logs:**
_crawler_1  | 2021-01-26 18:57:15,869 - elasticsearch - 139927523207968 - *********/********* - INFO - POST http://elastic:9200/monocle.changes.*********/_search [status:200 request:0.008s]
crawler_1  | 2021-01-26 18:57:15,869 - monocle.github.pullrequest - 139927523207968 - *********/********* - INFO - Running request {'org': '*********', 'repository': '*********', 'updated_since': datetime.datetime(2021, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': '', 'total_prs_count': 0, 'size': 100}
crawler_1  | 2021-01-26 18:57:17,134 - monocle.crawler - 139927523207968 - *********/********* - **ERROR - Unable to get PR data**
crawler_1  | Traceback (most recent call last):
crawler_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-0.7.0-py3.9.egg/monocle/crawler.py", line 100, in run_step
crawler_1  |     prs = self.prf.get(updated_since)
crawler_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-0.7.0-py3.9.egg/monocle/github/pullrequest.py", line 301, in get
crawler_1  |     hnp = self._getPage(kwargs, prs)
crawler_1  |   File "/usr/local/lib/python3.9/site-packages/monocle-0.7.0-py3.9.egg/monocle/github/pullrequest.py", line 251, in _getPage
crawler_1  |     kwargs["total_prs_count"] = data["data"]["repository"]["pullRequests"][
crawler_1  | **TypeError: 'NoneType' object is not subscriptable**
crawler_1  | 2021-01-26 18:57:17,134 - monocle.crawler - 139927523207968 - *********/********* - INFO - Waiting 10 seconds before next fetch ..._

OS: Windows

When I tried with an incorrect git token, it fails with an authentication error as expected on the crawler logs. When I have the right token I don't see that error. So I think I am using the right token and token does not  seem to be the issue.

When I point the config to a public github repo, it fetches the PR details. 

I am not sure how or what else I can do to debug or identify what the issue is with my private repo.

Any leads would be appreciated. Thanks..

**Comment by morucci** [comment]
Hi,

Yes at least a Personal Access Token with the "repo" scope is needed. I tested with a token w/o any specific scope and I got the same exception.
See https://github.com/change-metrics/monocle/pull/288

Let us know if this fix your issue.
Thanks for the report.

**Comment by sooraj19** [comment]
Hi @morucci , Thank you very much for checking and providing the information. It worked for me after I created a Personal Access Token with the "repo" scope as you suggested.

I also checked your PR and left a minor comment there.. 

I am happy to close this issue.

Thank you for the support.. 👍
