### ISSUE TITLE
demo instance configuration is not open sourced

### ISSUE THREAD

**Issue by ssbarnea** [change-metrics/monocle#312]
As I am one of those that find the https://demo.changemetrics.io being directly useful, I observed that there is no way to contribute back and improve it.

For example, out out `ansible-community` organization lists only one repository included in ansible tenant, which is obviously skewing the stats considerably. Instead of me asking to add new repos, would't be better to just propose a change? I swill do not know where to propose such a change as I do not see a repo under the org neither a link in the website mentioning where the configuration comes from.

**Comment by danpawlik** [comment]
Hi @ssbarnea,
As you know from the README file, the configuration provide Github Token which is confident and it should not be exposed, so to public configuration from demo instance require some work to do.
There is also an example of advanced configuration: https://github.com/change-metrics/monocle#full-configuration-file-example,
which is describing more.
It is a demon instance, that does not have a lot of hardware resources so we don't take each repository from ansible-community, but you should be able to do that without any issue.

If you will have any issue on starting docker-compose or podman compose (https://github.com/change-metrics/monocle/pull/309) please share it. We would be grateful to get some feedback about that.

**Comment by ssbarnea** [comment]
The current list of repos does include only the `ansible-lint` from ansible-community, which is has fewer repos than ansible-collections and unlikely to grow as fast as the collections. If you could also include this subset to the demo it would be great, especially as the current listing is misleading. Both ansible-lint and molecule were originally hosted under ansible main org but were moved outside to ease addition of new contributors.

The repositories listed below are likely to fit under a less than a couple of megabytes so I doubt they would affect the demo instance.
```
"https://github.com/ansible-community/ansible-lint"
"https://github.com/ansible-community/ara"
"https://github.com/ansible-community/ara-collection"
"https://github.com/ansible-community/ara-infra"
"https://github.com/ansible-community/ara-web"
"https://github.com/ansible-community/molecule"
"https://github.com/ansible-community/molecule-alicloud"
"https://github.com/ansible-community/molecule-azure"
"https://github.com/ansible-community/molecule-containers"
"https://github.com/ansible-community/molecule-digitalocean"
"https://github.com/ansible-community/molecule-docker"
"https://github.com/ansible-community/molecule-ec2"
"https://github.com/ansible-community/molecule-gce"
"https://github.com/ansible-community/molecule-goss"
"https://github.com/ansible-community/molecule-hetznercloud"
"https://github.com/ansible-community/molecule-inspec"
"https://github.com/ansible-community/molecule-libvirt"
"https://github.com/ansible-community/molecule-linode"
"https://github.com/ansible-community/molecule-lxd"
"https://github.com/ansible-community/molecule-openstack"
"https://github.com/ansible-community/molecule-podman"
"https://github.com/ansible-community/molecule-testinfra"
"https://github.com/ansible-community/molecule-vagrant"
"https://github.com/ansible-community/pytest-molecule"
"https://github.com/ansible-community/schemas"
"https://github.com/ansible-community/sphinx_ansible_theme"
"https://github.com/ansible-community/toolset"
"https://github.com/ansible-community/tox-ansible"
"https://github.com/ansible-community/vscode-ansible"
```

As we have the next contributors summit on [March 9th](https://www.eventbrite.com/e/ansible-contributor-summit-202103-registration-141735886853?aff=twitter), it would be really cool to be able to demo change-metrics there too.

**Comment by morucci** [comment]
Hello @ssbarnea 

Thanks for the feedback. As @danpawlik mentioned the configuration file contains a GH token. But we could still expose it w/o the token in a dedicated repository. I agree that it is easier to have people more aware than us about where project' repositories are located (especially Ansible where stuff move really fast) to update the config.

So I'll work on the some changes on demo instance playbook to make your proposal available soon. I'll keep you updated.

PS: in the meantime we could add ansible-community org into the config. The fact we only have the ansible-lint from ansible-community is probably because a org move.

Fabien

**Comment by morucci** [comment]
@ssbarnea ansible-community has been added: https://demo.changemetrics.io/ansible/repos

**Comment by ssbarnea** [comment]
Thanks! Now the new graphs are showing something I was not sure I wanted to be so easily exposed ;)

Externalizing the secret could make it much easier to contribute to the repository as I am sure there are other cool improvements that can be make, like adding excludes for bot users, user aliases/mappings and maintenance of repository list.

**Comment by morucci** [comment]
Yes excludes for bot users and user aliases/mappings are features I'd like to expose in the configuration file, but still I need to implement those features :)

**Comment by morucci** [comment]
Hi @ssbarnea FYI I've created https://github.com/change-metrics/demo-node-config. There no automation behind it yet but at least you can propose changes to the configuration.

**Comment by morucci** [comment]
I'm closing the issue. Please re-open if any concern about the provided solution.
