### ISSUE TITLE
:star: Allow deployment on `monocle` to openshift/k8s

### ISSUE THREAD

**Issue by georgettica** [change-metrics/monocle#320]
### Describe the feature or problem you’d like to solve

Currently the deployment is primarily used in docker-compose, while our hosting platform is k8s/openshift

### Proposed solution

we want to add an ansible-playbook which would deploy monocle on an k8s/openshift cluster

### Additional context

we are thinking of migrating some information (partially copy the `deploy` folder)  from [this source repo](https://github.com/rh-deliverypipeline/batyam)

**Comment by georgettica** [comment]
@lioramilbaum @guy9050

**Comment by morucci** [comment]
Hello @georgettica,

Thanks for starting the discussion.

After some reading I think the direction I'd like we explore for an official (supported) way of deploying in k8s is the operator pattern. I'd like to have built-in solution to manage monocle maintenance and it seems we can provide that logic through an operator.

But today, that seems overkill and I'd like we simply create the k8s maniftest to deploy in k8s or OpenShift.
I'd like to have resources definition independent from a deployment framework like Ansible or Helm. So having a manifest that I can apply through kubeclt seem enough as of now.

Probably later, this manifest will need to be customizable so as a next step I'd like to explore solution like dhall-kubernetes.

For the first step, what about creating a k8s directory at the root of the project and provide the monocle.yaml  manifest ?

Let me know.

@flepied, @danpawlik feel free to jump in the conversion.

**Comment by lioramilbaum** [comment]
@morucci Your approach is valid. This is a good MVP for k8s/openshift deployment automation.

**Comment by morucci** [comment]
@lioramilbaum I can assign that story to any participants in that thread. So I can assign it to you or to @georgettica. Let me know :)

**Comment by georgettica** [comment]
Assign to me :)

**Comment by georgettica** [comment]
the current state is the PR #489 is driving alot of the work.

additional issue was created and addressed at #509 to make deployment smoother

so far we are on the roadmap (maybe not for 1.0 as that version I think was already cut, but to 1.1 )
