### ISSUE TITLE
Change API for crawler

### ISSUE THREAD

**Issue by TristanCacqueray** [change-metrics/monocle#404]
The goal of this story is to define a new API suitable to implement change crawler. It will be used for GitLab. The goal is to define a updateable entities by oldest order: *organization* and *project*:

For each entity (or system api), the api let you query the oldest element, for example:

Base api:

- Monocle.Backend.get_last_updated :: entity_type -> m [entity]
- Monocle.Backend.updated_last_updated_at :: entity_type -> entity -> utctime -> m ()

For the *organzation* entity:

- Lentille.fetch_project :: organization -> m [project]
- Monocle.Backend.add_project :: organization -> [project] -> m ()

```haskell
projectCrawler = do
  lasted_updated_at <- getCurrentTime
  oldest_org <- Monocle.Backend.get_last_updated "organization"

  projects <- Lentille.fetch_project oldest_org
  Monocle.Backend.add_project oldest_org projects

  Monocle.Backend.updated_last_updated_at "organization" oldest_org latest_udpated_at
```

For the *project* entity:

- Lentille.fetch_pr :: project -> m [pr]
- Lentille.fetch_pr_commits :: change -> m [commits]
- Monocle.Backend.change_add :: [documents] -> m ()

```haskell
prCrawler = do
  lasted_updated_at <- getCurrentTime
  oldest_project <- Monocle.Backend.get_last_updated "project"

  pr <- Lentille.fetch_pr oldest_project
  -- stop when pr age > oldest_project age
  commits <- Monocle.Backend.change_add pr
  let changes = toDocuments pr commits
  Monocle.Backend.change_add changes

  Monocle.Backend.updated_last_updated_at "project" oldest_project latest_udpated_at
```

**Comment by TristanCacqueray** [comment]
Is this really completed?

**Comment by morucci** [comment]
Oh no this is Github that close automatically because the linked PR is merged
