### ISSUE TITLE
monocle_api-ng_1 container always ends up "unhealthy" after starting; no data shows

### ISSUE THREAD

**Issue by Hixie** [change-metrics/monocle#416]
I tried following the steps in the README:
1. Installed `Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2` using `apt`. Added myself to the `docker` group, rebooted to be sure.
2. I configured my `etc/config.yaml` as follows:
```
tenants:
  - index: monocle
    crawler:
      loop_delay: 10
      github_orgs:
        - name: flutter
          updated_since: "1980-01-01"
          token: ghp_redactedredactedredactedredacted
          base_url: https://github.com
```
(I'm not sure if the updated_since line is a problem; it wasn't clear to me what that should be set to.)
3. I configured my `.env` as follows to avoid clashing with the unifi software that's using port 8080:
```
MONOCLE_PUBLIC_URL=http://localhost:1200
MONOCLE_VERSION=latest
MONOCLE_TITLE=Flutter Monocle
#MONOCLE_API_ADDR=0.0.0.0
#MONOCLE_API_PORT=9876
#MONOCLE_WEB_ADDR=0.0.0.0
MONOCLE_WEB_PORT=1200
#MONOCLE_ELASTIC_ADDR=0.0.0.0
#MONOCLE_ELASTIC_PORT=9200
```
4. `docker-compose up -d`
5. This is the state I end up in after a few seconds:
```
ianh@burmese:~/dev/monocle$ docker-compose ps
      Name                     Command                   State                Ports
--------------------------------------------------------------------------------------------
monocle_api-ng_1    monocle-api --port 9898          Up (unhealthy)   0.0.0.0:9898->9898/tcp
monocle_api_1       uwsgi --http :9876 --socke ...   Up (healthy)     0.0.0.0:9876->9876/tcp
monocle_crawler_1   monocle --elastic-conn ela ...   Up
monocle_elastic_1   /tini -- /usr/local/bin/do ...   Up (healthy)     9200/tcp, 9300/tcp
monocle_web_1       /bin/sh -c /bin/start.sh         Up               0.0.0.0:1200->8080/tcp
```
When I run `docker-compose logs -f api-ng` I see this:
```
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:35:56 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:35:56 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:35:56 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:46:52 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:46:52 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
api-ng_1   | 172.19.0.6 - - [14/Jun/2021:18:46:52 +0000] "POST /api/2/search/changes HTTP/1.1" 200 - "http://localhost:1200/monocle/board" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
```
When I run `docker-compose logs -f crawler` I see this:
```
crawler_1  | 2021-06-14 19:01:30,607 - root - 140029065049664 - flutter/flutter - INFO - page oldest updated at date is 2020-10-20 06:23:06+00:00
crawler_1  | 2021-06-14 19:01:30,607 - monocle.github.pullrequest - 140029065049664 - flutter/flutter - INFO - 5437 PRs fetched
crawler_1  | 2021-06-14 19:01:30,607 - monocle.github.pullrequest - 140029065049664 - flutter/flutter - INFO - Running request {'org': 'flutter', 'repository': 'flutter', 'updated_since': datetime.datetime(1980, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': 'after: "Y3Vyc29yOnYyOpK5MjAyMC0xMC0xOVQyMzoyMzowNi0wNzowMM4d6-Ha"', 'total_prs_count': 28500, 'size': 45}
crawler_1  | 2021-06-14 19:01:42,077 - monocle.github.graphql - 140029065049664 - flutter/flutter - ERROR - Errors in response: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `B978:0E0E:AF9630:BEB359:60C7A78B` when reporting this issue.'}]}
crawler_1  | 2021-06-14 19:01:42,077 - monocle.github.pullrequest - 140029065049664 - flutter/flutter - INFO - Running request {'org': 'flutter', 'repository': 'flutter', 'updated_since': datetime.datetime(1980, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': 'after: "Y3Vyc29yOnYyOpK5MjAyMC0xMC0xOVQyMzoyMzowNi0wNzowMM4d6-Ha"', 'total_prs_count': 28500, 'size': 22}
crawler_1  | 2021-06-14 19:01:47,444 - root - 140029065049664 - flutter/flutter - INFO - page oldest updated at date is 2020-10-19 19:28:47+00:00
crawler_1  | 2021-06-14 19:01:47,444 - monocle.github.pullrequest - 140029065049664 - flutter/flutter - INFO - 5459 PRs fetched
crawler_1  | 2021-06-14 19:01:47,444 - monocle.github.pullrequest - 140029065049664 - flutter/flutter - INFO - Running request {'org': 'flutter', 'repository': 'flutter', 'updated_since': datetime.datetime(1980, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'after': 'after: "Y3Vyc29yOnYyOpK5MjAyMC0xMC0xOVQxMjoyODo0Ny0wNzowMM4eHooE"', 'total_prs_count': 28500, 'size': 25}
```
(Note in particular the GitHub error? Not sure if that's related.)

When I go to http://localhost:1200/monocle, I don't see any data at all, everything is blank, zeroes, empty.

**Comment by TristanCacqueray** [comment]
The unhealthy message is happening because the health endpoint does not exists yet, #417 should fix that.

The page should not be empty though, what happens if you go to http://localhost:1200 ?

**Comment by Hixie** [comment]
There is no data to speak of. For example, if I go to http://localhost:1200/monocle/repos?gte=2011-06-14&relativedate=10+years+ago the repositories summary is empty. Every page has headers but no data.

**Comment by Hixie** [comment]
I can include more of the crawler logs if that would help. I wonder if the problem is just that GitHub is not returning useful data -- the error in the logs above (`crawler_1  | 2021-06-14 19:01:42,077 - monocle.github.graphql - 140029065049664 - flutter/flutter - ERROR - Errors in response: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `B978:0E0E:AF9630:BEB359:60C7A78B` when reporting this issue.'}]}`) is worrying in particular.

**Comment by TristanCacqueray** [comment]
The error is not good indeed, but the crawler does seem to fetch some of the PRs, so there should be results in the pages.

**Comment by morucci** [comment]
The error returned by the GH API is logged and then correctly handled by the crawler. This error might occur quite often during the process. It means that the GH API timeouted. Indeed the initial crawling of a repo might be quite intensive (here I see ~28000 PRs). PRs are fetched by the crawler by page of 100 PRs. As for each page it might fail (timeout) (this depends on the amount of associated metadata: amount of commit/events),  the crawler decreases/increases automatically the amount of PRs asked by page.  So do not worry to much about this error as the crawler will adapt and continue to fetch data.

See the query that is performed: https://github.com/change-metrics/monocle/blob/master/monocle/github/pullrequest.py#L156

Also note that the crawler will index data in the DB at the end of the crawling process of the repo. Until then nothing will be displayed in the UI.

**Comment by Hixie** [comment]
Ah! I wasn't clear on when to expect data. In that case, sounds like everything is working perfectly. Thanks so much! I can't wait to see the data!

**Comment by Hixie** [comment]
The data appeared, and it looks great. Thanks!
