### ISSUE TITLE
"graph of the complexity versus time to merge changes" not available?

### ISSUE THREAD

**Issue by Hixie** [change-metrics/monocle#419]
In the README there's a sample "graph of the complexity versus time to merge changes", but going through the UI that graph does not seem available in the actual dashboard.

**Comment by faiqmustaqeem** [comment]
+1.

**Comment by morucci** [comment]
Hi

The graph is displayed in the "changes" view (click on display stats) but
only when the filter is set to state:MERGED.



Le sam. 19 juin 2021 à 21:02, Faiq Mustaqeem ***@***.***> a
écrit :

**Comment by faiqmustaqeem** [comment]
Thanks @morucci. found it
