### ISSUE TITLE
Replace the filterform with search query

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#468]
The goal is to unify the web interface using the new search query. The filterform based query needs to be rewritten using the new API.

- [x] Migrate the Activity view.
- [x] Migrate the People view.
- [x] Migrate the Project view.
- [x] Migrate the Changes view.
- [x] Investigate if Hot/Cold change is worthty to be migrated. https://github.com/change-metrics/monocle/issues/527
- [x] Remove the legacy react-router and the 'BaseQueryComponent'.

**Comment by TristanCacqueray** [comment]
Project view is in progress through https://github.com/change-metrics/monocle/pull/452
