### ISSUE TITLE
Web interface improvements

### ISSUE THREAD

**Issue by TristanCacqueray** [change-metrics/monocle#548]
* Changes view
- [x] Hide conflict label when change is merged
- [x] Change the MERGED label color

* Sort improvements
- [x] Set the change order by default
- [x] Reduce the available sort by fields

* Filter improvements
- [ ] Migrate project suggestions to apiv2 and group suggestion
- [x] Add date selector for from and to
- [ ] Add project and group selector
- [x] Move the existing free form selector to a `Other field section` (state, repo, author, branch, approval, priority, severity, task, score)
- [x] When the modal is closed, automatically apply
- [x] Support enter key to apply

* Interface improvements
- [x] Update navigation link with the current query and filter
- [x] Ensure the padding/margin are consistent accross the view
- [x] Fix the new contributor query
- [ ] Migrate group and workspace list to tables
- [ ] Remove the remaining bootstrap
- [ ] Add horizontal scroll bar to the board page

**Comment by morucci** [comment]
Let's close this and move forward with https://github.com/change-metrics/monocle/issues/559
