### ISSUE TITLE
Crawler metadata not created on auto-reload of config

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#589]
The API is able to reload the configuration file when changed, however crawler metadata are not refreshed thus Macroscope fails to get initial entity metadata.

**Comment by TristanCacqueray** [comment]
It seems like we shouldn't have to init the crawler metadata. When we can't find the last updated, we could simply returns:

```haskell
(
    ( getProjectEntityFromCrawler crawler
        <> maybe [] (: []) (getOrganizationEntityFromCrawler crawler)
    )
, (getWorkerUpdatedSince crawler)
```
