### ISSUE TITLE
Expose Work-in-progress from Gerrit

### ISSUE THREAD

**Issue by flepied** [change-metrics/monocle#687]
An idea would be to expose it like the draft status of Github.

**Comment by morucci** [comment]
- [ ] Update gerrit-haskell to support work_in_progress status
- [ ] Release gerrit-haskell and publish on Hackage
- [ ] Update the Monocle Gerrit crawler to set the correct draft status

**Comment by morucci** [comment]
A followup will be https://github.com/change-metrics/monocle/issues/981
