### ISSUE TITLE
🦥 : web js and css are heavy (causing long load times)

### ISSUE THREAD

**Issue by georgettica** [change-metrics/monocle#724]
I saw they are both a few megs in size, which causes the startup of the web component to be fairly slow for development :(

**Comment by morucci** [comment]
We still bundle bootstrap-react as it was our previous CSS lib before we moved to Patternfly.
We still have few components that use bootstrap. I'll move forward and remove the bootstrap dep. Thanks for the head up !

**Comment by giacomocerquone** [comment]
as far as I can see, bootstrap-react isn't listed anymore in the [package.json](https://github.com/change-metrics/monocle/blob/master/web/package.json)

Should this be closed?

**Comment by morucci** [comment]
Thanks for the heads up ! Yes let's close it.
