### ISSUE TITLE
Add GHA validation for the Kube deployment

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#725]
To protect ourself to break the deployment w/o noticing it then it might be more secure to add a GitHub action to validate the deployment.

**Comment by morucci** [comment]
@georgettica would you like to tackle this issue ?

**Comment by georgettica** [comment]
Sure!

**Comment by georgettica** [comment]
created PR, and it seems we didn't even need to change the k8s resources (I used the strict option)

**Comment by morucci** [comment]
@georgettica how could we have a GHA that run a kube deployment then verify that all pods are running ?

**Comment by georgettica** [comment]
yeah, I can do that :)
but what would kind of validation would you want to run?
also, I will change in there the type of the `crawler-legacy` to Job so it doesn't run all the time

**Comment by georgettica** [comment]
@morucci is there something else I can do here?
I guess the things we discussed before with the cronjob and such, but is this validation ok for now?

**Comment by morucci** [comment]
Yes you are right we can close this issue. Thanks for the heads up !
