### ISSUE TITLE
TaskData must not use b64.encode(TDurl <> TDChangeUrl) as EL Document ID (Limit is 512 Bytes)

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#845]
DOD: The function Index.getBase64Text should be wrapped in a hash function to ensure we don't go beyond the ID limit size.

https://www.joshmlwood.com/elasticsearch-ids-are-hard/

- [ ] Update the getBase64 function
- [ ] Provide a DB migration process (Mechanic already exists)

**Comment by TristanCacqueray** [comment]
And we need a migration function to rename the old document id right?

**Comment by morucci** [comment]
Indeed !

**Comment by morucci** [comment]
After a deeper look, I see that we do not rely on the DocId content so a migration process does not seem needed.
