### ISSUE TITLE
[spec] implement support of OpenID Connect (Web UI)

### ISSUE THREAD

**Issue by mhuin** [change-metrics/monocle#874]
This spec aims to add support for authentication via OpenID Connect in Monocle. This mode of authentication will be optional, meaning that if not set in the application's configuration, the legacy authentication workflow will be enforced by default. Both authentication modes will be mutually exclusive. This spec complements [ADR 12: OpenID Connect Authentication](https://github.com/change-metrics/monocle/blob/master/doc/adr/0012-OpenID-connect-authentication.md).

# Current state

The notion of *user* is relevant to searches in the web GUI. The search endpoint of the Monocle API accepts an "ident" argument, which corresponds to the user's full name. The Monocle backend then converts this ident to known aliases on providers for searches.

## Current Auth workflow

1. A user "logs in" on the GUI by filling out a form with their full name.
2. The GUI calls the `validate` endpoint of the Monocle API server to ensure the user has associated records.
3. if the validation call succeeds, the username is stored into the React App store.
4. Whenever the user runs search queries, the GUI calls the `search` endpoint of the Monocle API server with the username parameter set to the username present in the store.
5. On logging out, the store is purged of the username.

# Proposed change

* Implement OpenID Connect auth support in the GUI with one of the available OIDC React libraries. The OIDC config (authority URL, Client ID, scope) can be passed to the React app as build env variables. If none of the variables are passed, the legacy authentication will be used instead.
* Add a route and page in the GUI to handle the authentication callback.

## New Auth workflow with OIDC

1. A user clicks on the "Log in" button on Monocle's GUI.
2. The user is redirected to an Identity Provider, and authenticates themselves.
3. Upon successful authentication, the user is redirected to the callback page, where the user's id token is processed so that the `preferred_username` claim is mapped to the app store's username, similarly to step 3 in the current workflow.
4. Whenever the user runs search queries, the GUI calls the `search` endpoint of the Monocle API server with the username parameter set to the username present in the store.
5. On logging out, the store is purged of the username.

As we can see, the change will only impact the GUI. The existing workflow involving the backend will be kept as is.

# Impact

- A new javascript dependency will be required to handle the auth workflow.

# Limitations

This change simply shifts the "responsibility" of providing a username from the user themselves to an Identity Provider. This does not solve the existing impersonation issue with the backend; it just ensures that users of the web UI are already validated by a third party. 

# Follow-ups

The next step will be to add support for id tokens directly in the search endpoint, so that user impersonation is not possible. It would also make it possible to enforce scoping searches to oneself only for certain users. This will require a way to validate id tokens in the backend. This is discussed in https://github.com/change-metrics/monocle/issues/877 .

# 06/07/2022 - Amending

After some testing we've figured out that the *OIDC Implicit flow* implemented via the Monocle WEB App will lack of flexibility and probably limit the integration of Monocle with various OIDC OP. Then it has been decided to rely on the backend part to handle the *OIDC Authorization code flow*.

This makes the web APP side implementation much simpler. Here are the required tasks:

- [X] Ensure the about endpoint is fetched before initialize the store 
- [x] Inspect the local storage to look for the JWT
- [x] When authentication enabled and JWT absent or invalid then display the login page
- [x] Login page displays a button to invite to login with the Authentication provider
- [x] Add a timer that trigger the Login page display (delete the token from the storage) when the JWT expired
- [x] Pass the JWT to API call if available in the store

**Comment by morucci** [comment]
Thanks you @mhuin for the specification.

Some comments:
- Change: "Auth workflow" -> "Current Auth workflow"
- Regarding the workflow "Auth workflow with OIDC" I don't think we need to validate if the `preferred_username` owns some changes or events as a extra step of the authentication flow. This step just made sense with the current login system.

The main problem I see and this is what you mention in the "Follow-ups" section is that it is easy to impersonate a user as the backend trusts the client (the webapp). Then we need to tackle that issue an be able to validate the id token server side.

So it seems we need a configuration server side to enable the OIDC auth then we could leverage the *about* endpoint to tell the webapp to authenticate users. Then the backend should expected an *id_token* either as POST data for queries or via a HTTP Header attribute.

We could still pass the "username" attribute to search endpoints to keep the same API but we need ensure that the *id_token* is valid.

**Comment by TristanCacqueray** [comment]
`The existing workflow involving the backend will be kept as is.` seems to conflict with `the preferred_username claim is validated by the backend`, could you expand this more? I suggest you add a couple of sentences to explain what is the validation process.

This proposal seems to be GUI centric, but what about terminal user, how will that works out? I think it would be useful to also explain the low level implementation with curl, e.g. what is the token content and how it can be used for testing.

**Comment by mhuin** [comment]
> Thanks you @mhuin for the specification.
> 
> Some comments:
> 
>     * Change: "Auth workflow" -> "Current Auth workflow"

Done

>     * Regarding the workflow "Auth workflow with OIDC" I don't think we need to validate if the `preferred_username` owns some changes or events as a extra step of the authentication flow. This step just made sense with the current login system.
> 

Done

> The main problem I see and this is what you mention in the "Follow-ups" section is that it is easy to impersonate a user as the backend trusts the client (the webapp). Then we need to tackle that issue an be able to validate the id token server side.

I've created a follow-up spec: https://github.com/change-metrics/monocle/issues/877

> So it seems we need a configuration server side to enable the OIDC auth then we could leverage the `about` endpoint to tell the webapp to authenticate users. Then the backend should expected an _id_token_ either as POST data for queries or via a HTTP Header attribute.

Is the "about" endpoint loaded by the webapp at starting time? I think it's simpler to handle env variables when starting the app rather than load OIDC settings from a REST endpoint. (It is doable, however)

> We could still pass the `username` attribute to search endpoints to keep the same API but we need ensure that the `id_token` is valid.

**Comment by mhuin** [comment]
> `The existing workflow involving the backend will be kept as is.` seems to conflict with `the preferred_username claim is validated by the backend`, could you expand this more? I suggest you add a couple of sentences to explain what is the validation process.

@morucci suggested we can drop the validation call when authenticating with OIDC, so I removed this step from the spec.

> This proposal seems to be GUI centric, but what about terminal user, how will that works out? I think it would be useful to also explain the low level implementation with curl, e.g. what is the token content and how it can be used for testing.

It is GUI centric. It changes the way the GUI gets the username, by authenticating a user with third party Identity Provider rather than self-defined by the user. Everything else remains the same, so no impact on terminal users. For a possible support of OIDC tokens backend-size, see the follow-up spec: https://github.com/change-metrics/monocle/issues/877

**Comment by morucci** [comment]
Lets agree on actionable tasks:
- [ ] Bind required functions of https://www.npmjs.com/package/oidc-react for REScript
- [ ] webapp must fetch the about endpoint at startup and then store information in the store
- [ ] Login component must determine login behavior (unAuthencated login or openID) by checking the store
- [ ] Successful authentication must set the username in the webapp store
- [ ] Unsuccessful authentication must indicate to the user the authentication is denied
- [ ] An Authorization Header must be passed to backend with the JWT content

**Comment by TristanCacqueray** [comment]
https://github.com/authts/react-oidc-context seems rather straightforward too.
