### ISSUE TITLE
Unable to fetch Github ratelimit

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#876]
A token is used as the organization is private.

```
May 09 07:58:36 monocle bash[1900278]: , rlRequestBody = "{\"query\":\"\\n    query GetRateLimit  {\\n      rateLimit {\\n        used\\n        remaining\\n        resetAt\\n      }\\n    }\\n  \",\"operationName\":\"GetRateLimit\",\"variables\":null}", rlResponse = Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, >
```

**Comment by TristanCacqueray** [comment]
Is the log complete? I am not sure to understand what is this issue about. Could you explain it more please?

**Comment by morucci** [comment]
Sorry, yes it lacks a bit of information. Actually the issue was that a github url was specified in the monocle config for this crawler. The url missed the "/api/graphql" path, thus the 404. Solution was to remove the setting to default on the default github.com/api/graphql url.
