### ISSUE TITLE
Trim whitespace for author.muid

### ISSUE THREAD

**Issue by ttruong-dexcom** [change-metrics/monocle#973]
**Update** on closer inspection the extra character is not whitespace. Some weird character that can't be rendered. 

Not sure if it's also applicable for other fields but author.muid includes whitespace which is hidden to the user in the UI.
Took me awhile to figure out why my filter was not working event though I typed the string correctly. See screenshot for example:

![image](https://user-images.githubusercontent.com/88852650/196814242-4052e543-b674-491d-a2e6-69bd71bc1f1c.png)

FYI I'm using Kibana in above screen to explore the data but this issue happens in Monocle WebUI

**Comment by morucci** [comment]
Hi, thanks for the report.

This is weird, as the author's login from a Github PR is not modified by Monocle and should be displayed and be usable as it was in the crawled PR. However if authors aliases are defined into the Monocle configuration file the muid will be updated accordingly. Do you have a configuration for https://github.com/change-metrics/monocle#identity-management ?

Also trying on the demo node I'm able to search for dependabot's changes: https://demo.changemetrics.io/elastic/changes?q=from:now-3weeks%20and%20author:dependabot

You could set your Monocle filter like author:"dependabot " <- with quotes including the weird character if you could dump it from the network data.

**Comment by ttruong-dexcom** [comment]
@morucci Ok if you go here https://demo.changemetrics.io/elastic/active_authors?q=from%3Anow-3months+and+not+author%3Adependabot and scroll down to By changes reviewed why does it still show dependabot?

**Comment by morucci** [comment]
@ttruong-dexcom, yes this is a but that should be fixed by #977.
