### ISSUE TITLE
How exactly is complexity score calculated? 

### ISSUE THREAD

**Issue by ttruong-dexcom** [change-metrics/monocle#974]
Maybe I miss the definition somewhere. If not it should be in the README.

**Comment by TristanCacqueray** [comment]
The complexity is computed in the web interface using this formula: https://github.com/change-metrics/monocle/blob/5eb18c3d67757d4fad1d03423390552337531b0f/web/src/components/Change.res#L10-L13

This could probably be improved though, for example by ignoring comments or auto generated files. We are open to suggestion to improve the score.

**Comment by morucci** [comment]
Perhaps we can merge that #975 to remove the ambiguity then close this issue.

If the complexity computation is not satisfying (which I think it is not) then we should open another issue to discuss solution to improve it. For instance as being computed by the UI it makes it impossible to use in the query.
