### ISSUE TITLE
Just showing appreciation (+ hacktoberfest request)

### ISSUE THREAD

**Issue by giacomocerquone** [change-metrics/monocle#976]
Hey there!
Sorry to open an issue for this but I just love this project, it's exactly what I was looking for to try to improve the review process in my team.

Being a react dev I'd very much like to contribute if there is some front-end issue here!
In the meantime would you participate to [hacktoberfest](https://hacktoberfest.com/) just by adding that topic to your repo?

**Comment by morucci** [comment]
Hi,
Thanks for the great feedback !
Sure I just added the topic. I don't see any real issues on the front-end, however if you see room for improvement feel free to open an issue or even propose a PR.

**Comment by giacomocerquone** [comment]
Will do thanks
