### ISSUE TITLE
Error deploy Ingress

### ISSUE THREAD

**Issue by ctit-cl** [change-metrics/monocle#988]
I created an ingress element in my K8s Deploy with the variables in API Deploy.

    - name: MONOCLE_PUBLIC_URL
      value: https://mr.webdoxclm.com
    - name: MONOCLE_WEBAPP_TITLE
      value: WebdoxCLM

but I have this error in the validation of deployment.

![image](https://user-images.githubusercontent.com/52297338/201438370-aafa609e-20ed-4eea-ba1f-243b9370e3cd.png)

is it possible to create an ingress in Kubernetes or only local deploy with port-forward?

**Comment by morucci** [comment]
Hi, I don't see any error in the HTML output here. Sure an ingress resource can be declared to remove the need of the port forward.
