### ISSUE TITLE
Closed draft GitHub PR is considered as "Draft"

### ISSUE THREAD

**Issue by mochja** [change-metrics/monocle#993]
I'd expect closed Draft PR to be reported as "Abadoned" in the UI. Currently it reports as "Draft".

![image](https://user-images.githubusercontent.com/1218946/203399511-3aa0ab3b-7041-4bcd-9a1f-3f39bdb93969.png)

Change timeline shows that it was abandoned and commented as I have used "Close with Comment" functionality of GH.

![image](https://user-images.githubusercontent.com/1218946/203399849-a283caea-bfe3-4c06-8fb9-e49d3474d2f2.png)

**Comment by morucci** [comment]
Hi Ján,

Thanks for the report. That seems to be a bug indeed.
I'll provide a fix shortly.
